# This workflow will upload a Python Package using Twine when a release is created

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write  # This workflow needs write access to packages for upload

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specific version can be used if needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build  # Assuming build is required for packaging

      - name: Build package
        run: python -m build  # Build the package

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          # Replace with your actual project URL on PyPI
          url: https://pypi.org/project/BRIntel1/
          token: ${{ secrets.PYPI_API_TOKEN }}
